# Default values for ducks-tinder-client.

# This is to override the chart name.
nameOverride: ''

# This is for deployment settings
deployment:
  name: frontend-deployment
  replicaCount: 1
  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  image:
    repository: example/repository
    tag: latest
    pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /
      port: https
      scheme: HTTPS
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: https
      scheme: HTTPS
    initialDelaySeconds: 15
    periodSeconds: 10
  env: []
  resources: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# This is for service settings
service:
  name: ducks-tinder-client
  type: ClusterIP
  port: 80
  httpsPort: 443

# This is for external service settings
# Used to have main ingress for whole application
# and route to other namespaces
externalService:
  namespace: default

# This is for secret settings
secret:
  name: ducks-tinder-client-secret
  mode: prod
  proxyMode: prod

  serverName: localhost
  proxyDns: 8.8.8.8
  proxyDnsValidTime: 30s
  certPath: /etc/nginx/cert/tls.crt
  keyPath: /etc/nginx/cert/tls.key
  proxyRootPath: /

  userServiceUrl: https://localhost/user-service-url
  chatServiceUrl: https://localhost/chat-service-url
  fileServiceUrl: https://localhost/file-service-url
  authServiceUrl: https://localhost/auth-service-url

  proxyUserService: /user-service-url
  proxyChatService: /chat-service-url
  proxyFileService: /file-service-url
  proxyAuthService: /auth-service-url

  proxyUserServiceUrl: https://host.docker.internal:5000
  proxyChatServiceUrl: https://host.docker.internal:5001
  proxyFileServiceUrl: https://host.docker.internal:5002
  proxyAuthServiceUrl: https://host.docker.internal:5003

  rootPath: /

# This is for certificate settings
certificate:
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: client-issuer
    kind: Issuer
    group: cert-manager.io
