apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-certificate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: "{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
  dnsNames:
    - "{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
  secretName: frontend-tls
  privateKey:
    {{- toYaml .Values.certificate.privateKey | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
