apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
type: Opaque
data:
  VAR_MODE: {{ .Values.secret.mode | b64enc | quote }}

  VAR_CLIENT_ROOT_URL: {{ .Values.secret.clientRootUrl | b64enc | quote }}
  VAR_USER_SERVICE_URL: {{ .Values.secret.userServiceUrl | b64enc | quote }}
  VAR_CHAT_SERVICE_URL: {{ .Values.secret.chatServiceUrl | b64enc | quote }}
  VAR_CHAT_SERVICE_SOCKET_PATH: {{ .Values.secret.chatServiceSocketPath | b64enc | quote }}
  VAR_FILE_SERVICE_URL: {{ .Values.secret.fileServiceUrl | b64enc | quote }}
  VAR_AUTH_SERVICE_URL: {{ .Values.secret.authServiceUrl | b64enc | quote }}

  PROXY_USER_SERVICE: {{ .Values.secret.proxyUserService | b64enc | quote }}
  PROXY_CHAT_SERVICE: {{ .Values.secret.proxyChatService | b64enc | quote }}
  PROXY_FILE_SERVICE: {{ .Values.secret.proxyFileService | b64enc | quote }}
  PROXY_AUTH_SERVICE: {{ .Values.secret.proxyAuthService | b64enc | quote }}

  PROXY_USER_SERVICE_URL: {{ .Values.secret.proxyUserServiceUrl | b64enc | quote }}
  PROXY_CHAT_SERVICE_URL: {{ .Values.secret.proxyChatServiceUrl | b64enc | quote }}
  PROXY_FILE_SERVICE_URL: {{ .Values.secret.proxyFileServiceUrl | b64enc | quote }}
  PROXY_AUTH_SERVICE_URL: {{ .Values.secret.proxyAuthServiceUrl | b64enc | quote }}

  PROXY_SERVER_NAME: {{ .Values.secret.serverName | b64enc | quote }}
  PROXY_DNS: {{ .Values.secret.proxyDns | b64enc | quote }}
  PROXY_DNS_VALID_TIME: {{ .Values.secret.proxyDnsValidTime | b64enc | quote }}
  PROXY_CERT_PATH: {{ .Values.secret.certPath | b64enc | quote }}
  PROXY_KEY_PATH: {{ .Values.secret.keyPath | b64enc | quote }}
  PROXY_ROOT_PATH: {{ .Values.secret.proxyRootPath | b64enc | quote }}

  VAR_ROOT_PATH: {{ .Values.secret.rootPath | b64enc | quote }}
  {{- with .Values.secret.matomoUrl }}
  VAR_MATOMO_URL: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secret.matomoSiteId }}
  VAR_MATOMO_SITE_ID: {{ . | b64enc | quote }}
  {{- end }}
